version: '3.6'
services:
  postgres:
    image: postgres:10
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
    env_file: 
      - .env/db.dev.env
  graphql-engine:
    image: hasura/graphql-engine:v1.3.1
    ports:
    - "3100:8080"
    depends_on:
    - "postgres"
    restart: always
    env_file:
      - .env/hasura.dev.env
volumes:
  db_data: